### ISSUE TITLE
docs: 어느 문서부터 읽어야 할 지 모르겠어요. 

### ISSUE THREAD

**Issue by kybin** [baesy0/learningEnglish#5]
파일 명 앞에 숫자를 붙이거나, 
docs 디렉토리 안에 README.md 를 만들어 목차를 생성하면 좋을것 같아요.

**Comment by baesy0** [comment]
아 작성이 완료되지 않은 문서들은 일부러 README.md와 연결해 놓지 않았어요!
완성되는대로 연결할 예정입니다. 그러면 순서를 알 수 있을거에요!
고마워요😆
