### ISSUE TITLE
No를 이용해 부정문 만들 때 관사의 처리.

### ISSUE THREAD

**Issue by baesy0** [baesy0/learningEnglish#9]
I have a homework.
I have no homework.
에서 a를 안쓰는 게 맞는지.
그 이유는 뭔지.

**Comment by khw7096** [comment]
- 영어는 수를 세는것이 중요하다고 배웠습니다.
- 수업시간의 설명으로는 no homework는 homework가 없다는 것이기 때문에 샐 수 있는 homework가 없다.
- a 를 안쓰는 것이 감정상으로는 맞다고 생각해요.

**Comment by baesy0** [comment]
네 동의합니다! 관사가 없는 편이 더 자연스럽게 느껴지기도 하구요.
그렇지만 좀 더 확실한 설명을 찾고 싶었는데 잘 안나오네요!
`There is no homework in Finland`라는 예문은 하나 찾았어요.
관사는 안붙이는 게 맞는걸로!
